// Dummy data for the application

export const popularQuizzes = [
    {
      id: "1",
      title: "Technology",
      description:
        "Explore the world of technology with this interesting Technology Quiz. Challenge if you dare to put your knowledge to the test!",
      status: "published",
      timeLimit: 10,
      questionCount: 10,
      questions: [],
      createdAt: new Date().toISOString(),
      color: "#ea4c37",
    },
    {
      id: "2",
      title: "Science",
      description: "Test your knowledge of scientific principles and discoveries",
      status: "published",
      timeLimit: 15,
      questionCount: 15,
      questions: [],
      createdAt: new Date().toISOString(),
      color: "#29A0F3",
    },
    {
      id: "3",
      title: "History",
      description: "Journey through time with questions about major historical events",
      status: "published",
      timeLimit: 12,
      questionCount: 12,
      questions: [],
      createdAt: new Date().toISOString(),
      color: "#6366f1",
    },
    {
      id: "4",
      title: "Geography",
      description: "Explore countries, capitals, and natural wonders",
      status: "published",
      timeLimit: 8,
      questionCount: 8,
      questions: [],
      createdAt: new Date().toISOString(),
      color: "#ec4899",
    },
  ]
  
  export const recentlyPlayedQuizzes = [
    {
      id: "1",
      title: "Social sciences",
      score: 8,
      totalQuestions: 10,
      date: new Date().toISOString(),
      color: "#ea4c37",
      icon: "🧠",
    },
    {
      id: "2",
      title: "Mathematics",
      score: 7,
      totalQuestions: 10,
      date: new Date(Date.now() - 86400000).toISOString(),
      color: "#29A0F3",
      icon: "🔢",
    },
    {
      id: "3",
      title: "Literature",
      score: 9,
      totalQuestions: 10,
      date: new Date(Date.now() - 172800000).toISOString(),
      color: "#6366f1",
      icon: "📚",
    },
  ]
  
  export const quizDetails = {
    id: "1",
    title: "Technology Quiz",
    description: "Test your knowledge of technology",
    status: "published",
    timeLimit: 10,
    createdAt: new Date().toISOString(),
    questions: [
      {
        id: "q1",
        text: "What does CPU stand for?",
        options: [
          { id: "a", text: "Central Processing Unit" },
          { id: "b", text: "Computer Personal Unit" },
          { id: "c", text: "Central Processor Unifier" },
          { id: "d", text: "Central Process Utility" },
        ],
        correctAnswerId: "a",
      },
      {
        id: "q2",
        text: "Which company created the iPhone?",
        options: [
          { id: "a", text: "Google" },
          { id: "b", text: "Microsoft" },
          { id: "c", text: "Apple" },
          { id: "d", text: "Samsung" },
        ],
        correctAnswerId: "c",
      },
      {
        id: "q3",
        text: "What year was the first website created?",
        options: [
          { id: "a", text: "1985" },
          { id: "b", text: "1991" },
          { id: "c", text: "1995" },
          { id: "d", text: "2000" },
        ],
        correctAnswerId: "b",
        explanation: "The first website was created in 1991 by Tim Berners-Lee.",
      },
    ],
  }
  
  export const quizResult = {
    id: "result-123",
    quizId: "quiz-123",
    quizTitle: "Technology Quiz",
    totalQuestions: 10,
    correctAnswers: 7,
    wrongAnswers: 3,
    timeTaken: "8:45",
    questions: [
      {
        id: "q1",
        text: "What does CPU stand for?",
        options: [
          { id: "a", text: "Central Processing Unit" },
          { id: "b", text: "Computer Personal Unit" },
          { id: "c", text: "Central Processor Unifier" },
          { id: "d", text: "Central Process Utility" },
        ],
        correctAnswerId: "a",
        userAnswerId: "a",
        isCorrect: true,
      },
      {
        id: "q2",
        text: "Which company created the iPhone?",
        options: [
          { id: "a", text: "Google" },
          { id: "b", text: "Microsoft" },
          { id: "c", text: "Apple" },
          { id: "d", text: "Samsung" },
        ],
        correctAnswerId: "c",
        userAnswerId: "c",
        isCorrect: true,
      },
      {
        id: "q3",
        text: "What year was the first website created?",
        options: [
          { id: "a", text: "1985" },
          { id: "b", text: "1991" },
          { id: "c", text: "1995" },
          { id: "d", text: "2000" },
        ],
        correctAnswerId: "b",
        userAnswerId: "a",
        isCorrect: false,
        explanation: "The first website was created in 1991 by Tim Berners-Lee.",
      },
    ],
  }
  
  export const leaderboardData = {
    topUsers: [
      {
        id: "1",
        name: "Sophia Cao",
        rank: 1,
        score: 980,
        correctAnswers: 98,
        wrongAnswers: 2,
        avatar: "/placeholder.svg?height=100&width=100",
        color: "#ea4c37",
      },
      {
        id: "2",
        name: "Emma Ema",
        rank: 2,
        score: 950,
        correctAnswers: 95,
        wrongAnswers: 5,
        avatar: "/placeholder.svg?height=100&width=100",
        color: "#29A0F3",
      },
      {
        id: "3",
        name: "Andrew W",
        rank: 3,
        score: 920,
        correctAnswers: 92,
        wrongAnswers: 8,
        avatar: "/placeholder.svg?height=100&width=100",
        color: "#6366f1",
      },
      {
        id: "4",
        name: "Raya Gil Endawa",
        rank: 4,
        score: 890,
        correctAnswers: 89,
        wrongAnswers: 11,
        avatar: "/placeholder.svg?height=100&width=100",
        color: "#ec4899",
      },
      {
        id: "5",
        name: "Olivia Ava",
        rank: 5,
        score: 870,
        correctAnswers: 87,
        wrongAnswers: 13,
        avatar: "/placeholder.svg?height=100&width=100",
        color: "#8b5cf6",
      },
      {
        id: "6",
        name: "David Joshua",
        rank: 6,
        score: 850,
        correctAnswers: 85,
        wrongAnswers: 15,
        avatar: "/placeholder.svg?height=100&width=100",
        color: "#14b8a6",
      },
      {
        id: "7",
        name: "Charlotte Harper",
        rank: 7,
        score: 830,
        correctAnswers: 83,
        wrongAnswers: 17,
        avatar: "/placeholder.svg?height=100&width=100",
        color: "#f59e0b",
      },
      {
        id: "8",
        name: "Mia Evelyn",
        rank: 8,
        score: 810,
        correctAnswers: 81,
        wrongAnswers: 19,
        avatar: "/placeholder.svg?height=100&width=100",
        color: "#8b5cf6",
      },
    ],
    currentUser: {
      id: "current",
      name: "Current User",
      rank: 12,
      score: 750,
      correctAnswers: 75,
      wrongAnswers: 25,
      avatar: "/placeholder.svg?height=100&width=100",
      color: "#ea4c37",
    },
    quizStats: {
      averageScore: 78,
      highestScore: 98,
      lowestScore: 45,
      totalParticipants: 124,
    },
  }
  
  export const userProfile = {
    id: "user-123",
    name: "John Doe",
    email: "john.doe@example.com",
    avatar: "/placeholder.svg?height=100&width=100",
    quizHistory: [
      {
        id: "1",
        title: "Technology Quiz",
        date: new Date().toISOString(),
        score: 8,
        totalQuestions: 10,
        resultId: "result-1",
      },
      {
        id: "2",
        title: "Science Quiz",
        date: new Date(Date.now() - 86400000).toISOString(),
        score: 7,
        totalQuestions: 10,
        resultId: "result-2",
      },
      {
        id: "3",
        title: "History Quiz",
        date: new Date(Date.now() - 172800000).toISOString(),
        score: 9,
        totalQuestions: 12,
        resultId: "result-3",
      },
    ],
    achievements: [
      {
        id: "1",
        title: "Quiz Master",
        description: "Complete 10 quizzes with a score of 80% or higher",
        earnedDate: new Date(Date.now() - 86400000).toISOString(),
        icon: "🏆",
        color: "#ea4c37",
      },
      {
        id: "2",
        title: "Perfect Score",
        description: "Get a perfect score on any quiz",
        earnedDate: new Date(Date.now() - 172800000).toISOString(),
        icon: "🌟",
        color: "#29A0F3",
      },
      {
        id: "3",
        title: "Speed Demon",
        description: "Complete a quiz in less than half the allotted time",
        earnedDate: new Date(Date.now() - 259200000).toISOString(),
        icon: "⚡",
        color: "#6366f1",
      },
    ],
  }
  
  export const adminQuizzes = [
    {
      id: "1",
      title: "Technology Quiz",
      description: "Test your knowledge of technology",
      status: "published",
      timeLimit: 10,
      questions: [
        {
          id: "q1",
          text: "What does CPU stand for?",
          options: [
            { id: "a", text: "Central Processing Unit" },
            { id: "b", text: "Computer Personal Unit" },
            { id: "c", text: "Central Processor Unifier" },
            { id: "d", text: "Central Process Utility" },
          ],
          correctAnswerId: "a",
        },
        {
          id: "q2",
          text: "Which company created the iPhone?",
          options: [
            { id: "a", text: "Google" },
            { id: "b", text: "Microsoft" },
            { id: "c", text: "Apple" },
            { id: "d", text: "Samsung" },
          ],
          correctAnswerId: "c",
        },
      ],
      createdAt: new Date().toISOString(),
    },
    {
      id: "2",
      title: "Science Quiz",
      description: "Test your knowledge of scientific principles",
      status: "draft",
      timeLimit: 15,
      questions: [
        {
          id: "q1",
          text: "What is the chemical symbol for gold?",
          options: [
            { id: "a", text: "Go" },
            { id: "b", text: "Au" },
            { id: "c", text: "Ag" },
            { id: "d", text: "Gd" },
          ],
          correctAnswerId: "b",
        },
      ],
      createdAt: new Date(Date.now() - 86400000).toISOString(),
    },
    {
      id: "3",
      title: "History Quiz",
      description: "Test your knowledge of historical events",
      status: "published",
      timeLimit: 12,
      questions: [
        {
          id: "q1",
          text: "In what year did World War II end?",
          options: [
            { id: "a", text: "1943" },
            { id: "b", text: "1944" },
            { id: "c", text: "1945" },
            { id: "d", text: "1946" },
          ],
          correctAnswerId: "c",
        },
        {
          id: "q2",
          text: "Who was the first President of the United States?",
          options: [
            { id: "a", text: "Thomas Jefferson" },
            { id: "b", text: "John Adams" },
            { id: "c", text: "George Washington" },
            { id: "d", text: "James Madison" },
          ],
          correctAnswerId: "c",
        },
        {
          id: "q3",
          text: "What was the name of the first artificial satellite launched into space?",
          options: [
            { id: "a", text: "Sputnik 1" },
            { id: "b", text: "Explorer 1" },
            { id: "c", text: "Vanguard 1" },
            { id: "d", text: "Apollo 1" },
          ],
          correctAnswerId: "a",
        },
      ],
      createdAt: new Date(Date.now() - 172800000).toISOString(),
    },
  ]
  
  export const analyticsData = {
    totalQuizzes: 24,
    newQuizzes: 5,
    totalAttempts: 1248,
    newAttempts: 187,
    averageScore: 72,
    scoreChange: 3,
    attemptsOverTime: Array.from({ length: 30 }, (_, i) => ({
      date: new Date(Date.now() - i * 86400000).toLocaleDateString(),
      attempts: Math.floor(Math.random() * 50) + 20,
    })).reverse(),
    quizPerformance: [
      { title: "Technology", score: 78 },
      { title: "Science", score: 65 },
      { title: "History", score: 72 },
      { title: "Geography", score: 81 },
      { title: "Literature", score: 68 },
    ],
    popularQuizzes: [
      { title: "Technology", attempts: 320 },
      { title: "Geography", attempts: 280 },
      { title: "History", attempts: 240 },
      { title: "Science", attempts: 210 },
      { title: "Literature", attempts: 198 },
    ],
    topPerformers: [
      { name: "Sophia C.", score: 92 },
      { name: "Emma E.", score: 88 },
      { name: "Andrew W.", score: 85 },
      { name: "Raya G.", score: 82 },
      { name: "Olivia A.", score: 79 },
    ],
    userActivity: Array.from({ length: 30 }, (_, i) => ({
      date: new Date(Date.now() - i * 86400000).toLocaleDateString(),
      users: Math.floor(Math.random() * 30) + 10,
    })).reverse(),
  }
  
  export const defaultUser = {
    id: "user-123",
    name: "John Doe",
    email: "john.doe@example.com",
    avatar: "/placeholder.svg?height=100&width=100",
    role: "user",
  }
  
  